// 忽略错误4996，安全警告
#define _CRT_SECURE_NO_WARNINGS
#pragma once
//int devide();
//void scanfTest();
//int OJscanf();
//int FreopenTest();
//int primeTest();
//int dayNumber();
//int mulMatrix();
//int StrTest();
//int BinarySearchTest();
int LowBoundTest();